// Code generated by buildinfo. DO NOT EDIT.
package version

import (
	_ "embed"

	"github.com/UiP9AV6Y/buildinfo"
)

//go:generate buildinfo --generate buildinfo --filename buildinfo.json --project-dir ../..
//go:embed buildinfo.json
var embedInfo []byte
var buildInfo *buildinfo.BuildInfo

func init() {
	buildInfo = buildinfo.MustParse(embedInfo)
}

// Version returns the application release information
func Version() string {
	return buildInfo.VersionInfo.VersionRevision()
}

// Print returns version- and environment information.
func Print(program string) string {
	return buildInfo.Print(program)
}

// BuildInfo creates an independent copy of the internal
// build information.
func BuildInfo() *buildinfo.BuildInfo {
	return buildInfo.Clone()
}
