---

name: Test

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/*.yaml'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/*.yaml'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'

jobs:

  test-library:
    name: Test (Library)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test -v ./...

  lint-library:
    name: Lint (Library)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.56.0

  test-tools:
    name: Test (Tools)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'tools/go.mod'

    - name: Test
      working-directory: tools
      run: go test -v ./...

  lint-tools:
    name: Lint (Tools)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'tools/go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.56.0
        working-directory: tools

  build-tools:
    name: Build (Tools)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'tools/go.mod'

    - name: Build
      working-directory: tools
      run: go build -v ./...

